(add-to-list 'load-path (concat user-emacs-directory "/mine"))

(require 'mine-builtin)
(require 'mine-defuns)
(require 'mine-advice)
(require 'mine-bindings)
(require 'mine-desktop)
(require 'mine-pretty)
(require 'mine-packages)
(require 'mine-eshell)
(require 'mine-org)
(require 'mine-irc)
(require 'mine-jabber)
(require 'mine-mode-line)

(when (eq system-type 'darwin) (require 'mine-osx))
(when (eq system-type 'gnu/linux) (require 'mine-linux))

(setq mine-custom-dir (concat user-emacs-directory "/custom/"))
(defun load-custom-files ()
  (interactive)
  (when (file-exists-p mine-custom-dir)
      (let ((custom-files (directory-files mine-custom-dir t "\.el$")))
        (mapcar 'load-file custom-files))))

(load-custom-files)
(cd (getenv "HOME"))
(server-start)
(put 'dired-find-alternate-file 'disabled nil)
(put 'upcase-region 'disabled nil)
