(defconst jw-config-author-name "Joe Winder")
(defconst jw-config-author-email "jsph.winder+emacs@gmail.com")
(defconst jw-config-author-url "http://jwinder.io")
(defconst jw-config-github-url "https://github.com/jwinder/emacs")
(defconst jw-config-version "2.0.0")
