(defconst jw-config-author-name "Joe Winder")
(defconst jw-config-author-email "jsph.winder@gmail.com")
(defconst jw-config-author-url "http://jwinder.io")
(defconst jw-config-github-url "https://github.com/jwinder/emacs")
(defconst jw-config-version "2.7.1")
(defconst adamdecaf-config-github-url "https://github.com/adamdecaf/emacs.d")
(defconst knuckolls-config-github-url "https://github.com/knuckolls/knuckolls-emacs-config")
(defconst rubbish-config-github-url "https://github.com/rubbish/rubbish-emacs-setup")