(when (eq system-type 'darwin)
  (setq ns-command-modifier 'meta)
  (setq interprogram-paste-function 'x-selection-value)
  (setq browse-url-browser-function 'browse-url-default-macosx-browser)
  (setq ack-executable "ack")  
  )
