(deftheme mine-color
  "Originally inspired by the midnight-theme by Gordon Messmer (2001).")

(custom-theme-set-faces
 'mine-color
 '(default ((t (:background "black" :foreground "grey85"))))
 '(cursor ((t (:foreground "grey85"))))
 '(region ((t (:background "grey15"))))
 '(fringe ((t (:background "#252323"))))
 '(border-color ((t (:background "black"))))
 '(cursor-color ((t (:background "grey85"))))
 '(highlight-current-line-face ((t (:background "grey12"))))
 '(hl-line ((t (:background "#252323"))))
 '(font-lock-builtin-face ((t (:foreground "SkyBlue"))))
 '(font-lock-comment-face ((t (:italic t :foreground "grey60"))))
 '(font-lock-comment-delimiter-face ((t (:forground "grey60"))))
 '(font-lock-constant-face ((t (:forground "#1AB0B0"))))
 '(font-lock-function-name-face ((t (:foreground "SlateBlue"))))
 '(font-lock-keyword-face ((t (:foreground "Cyan"))))
 '(font-lock-string-face ((t (:foreground "#F261F2"))))
 '(font-lock-warning-face ((t (:bold t :foreground "Pink"))))
 '(font-lock-variable-name-face ((t (:foreground "DarkGoldenrod"))))
 '(font-lock-type-face ((t (:foreground "#008080")))) ;; dark cyan
 '(paren-face-match-light ((t (:background "grey30"))))
 '(highlight ((t (:background "blue"))))
 '(modeline ((t (:background "#3F3B3B" :foreground "white"))))
 '(modeline-buffer-id ((t (:background "#3F3B3B" :foreground "white"))))
 '(modeline-mousable ((t (:background "#a5baf1" :foreground "black"))))
 '(modeline-mousable-minor-mode ((t (:background "#a5baf1" :foreground "#000000"))))
 '(primary-selection ((t (:background "#3B3B3F"))))
 '(isearch ((t (:background "#555555"))))
 '(zmacs-region ((t (:background "#555577"))))
 '(secondary-selection ((t (:background "#545459"))))
 '(flymake-errline ((t (:background "LightSalmon" :foreground "#000000"))))
 '(flymake-warnline ((t (:background "LightSteelBlue" :foreground "#000000"))))
 '(underline ((t (:underline t))))
 '(minibuffer-prompt ((t (:bold t :foreground "SkyBlue"))))
 '(italic ((t (:italic)))))

(provide-theme 'mine-color)
